src/mServer/daten/MserverListeSuchen.java
src/mServer/daten/MserverListeUpload.java
src/mServer/search/MserverSearch.java
src/mServer/upload/MserverFtp.java

Ich habe alle Warnungen des Java-Compilers repariert bzw. unterdrückt.

Fix compiler warnings

---

src/dist/MServer.sh
src/dist/STOPPEN__MServer.sh

das vorherige stoppen im startscript klappte nicht

startscript

---

.travis.yml

Fixed travis deploy

---

src/main/java/mServer/crawler/CrawlerTool.java

Implementing #54 
Thanks @zxsd.

Added new Geo Blocking URL

---

build.gradle
src/main/java/mServer/crawler/sender/newsearch/ZDFClient.java
src/main/java/mServer/crawler/sender/newsearch/ZDFConfigurationDTO.java
src/main/java/mServer/crawler/sender/newsearch/ZDFConfigurationDTODeserializer.java
src/main/java/mServer/crawler/sender/newsearch/ZDFConfigurationLoader.java
src/main/java/mServer/crawler/sender/newsearch/ZDFEntryTask.java
src/main/java/mServer/crawler/sender/newsearch/ZDFSearchTask.java

This fixes #84 
I added a second api authentication code for the videos. Now they load again and no more 403.
The code for the videos will be loaded once per runtime from the [ZDF configuration](https://www.zdf.de/ZDFplayer/configs/zdf/zdf2016/configuration.json)
---
Für dich @alex1702 :
Ich habe jetzt den für die videos den 2. API code eingebaut welchen ich mir direkt aus der ZDF Configuration ziehe. ;)

Fixing #84

---

src/main/java/mServer/crawler/sender/MediathekArd.java
src/main/java/mServer/tool/M3U8Utils.java
src/test/java/mServer/tool/M3U8UtilsTest.java

- Added new M3U8 utils to get the MP4 files for M3U8 URLs from WDR.
- Added tests for M3U8 utils
Big thanks to @bagbag and for the hint to https://github.com/mediathekview/mediathekviewweb/issues/11
Thanks to @alex1702  for help at testing it.
Test log: http://80.77.26.245/loglang.log
Test filmliste result: http://80.77.26.245/filme.xz

Started to fix #104

---

src/main/java/mServer/crawler/sender/newsearch/ZDFClient.java

GZIP aktiviert

---

src/main/java/mServer/crawler/sender/MediathekArd.java

URLs ohne führendes http: ergänzen

---

src/main/java/mServer/crawler/sender/MediathekDw.java

Datum wird wieder ausgelesen

---

src/main/java/mServer/crawler/sender/MediathekDw.java

DW findet weitere Filme

---

src/main/java/mServer/crawler/sender/MediathekPhoenix.java

Fix Url für Videos

---

src/main/java/mServer/crawler/sender/arte/ArteJsonObjectToDatenFilmCallable.java

Bestückung von Titel und Thema umgestellt

---

src/main/java/mServer/crawler/sender/MediathekRbb.java

Added search for https urls to fix #180

Fixing #180

---

src/main/java/mServer/crawler/sender/MediathekWdr.java

Fix fehlendes Protokoll in Film-URLs

---

src/main/java/mServer/crawler/sender/arte/ArteVideoDetailsDeserializer.java
src/main/java/mServer/crawler/sender/newsearch/GeoLocations.java
src/test/developTest/java/mServer/crawler/sender/arte/ArteVideoDetailsDeserializerTest.java

Geo EU ersetzt durch DE_AT_CH_EU

---

src/main/java/mServer/crawler/sender/newsearch/ZDFSearchPageTask.java
src/main/java/mServer/crawler/sender/newsearch/ZDFSearchTask.java
src/main/java/mServer/crawler/sender/newsearch/ZDFVideoDTODeserializer.java

Fixed ZDF DTO building

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

Fix für Verwendung des Sendernamens

---

src/main/java/mServer/crawler/sender/MediathekKika.java

Fix: nur URLs der Sendung verarbeiten

---

src/main/java/mServer/crawler/sender/MediathekReader.java

weitere URL für ARD-Geo hinzugefügt

---

src/main/java/mServer/crawler/sender/newsearch/ZDFConfigurationDTODeserializer.java

Quickfix für ZDF-Suche #255.
Die saubere Lösung können wir dann in Ruhe implementieren.

Defaultwert für Bearer aktualisiert

---

src/main/java/mServer/crawler/sender/MediathekNdr.java

Fix HD-Erkennung NDR

---

src/main/java/mServer/crawler/sender/MediathekWdr.java
src/main/java/mServer/crawler/sender/MediathekZdf.java

Fix für die Stabilitätsprobleme des Crawlers

Fixes für Stabilität der Crawler

---

src/main/java/mServer/crawler/sender/MediathekReader.java

Geo erweitert

---

src/main/java/mServer/crawler/sender/MediathekReader.java

Geo für BR auch für https-URLs

---

src/main/java/mServer/crawler/sender/MediathekArd.java

HD-Url aus normaler Url "erraten"

---

src/main/java/mServer/crawler/sender/MediathekArd.java

Ermitteln der HD-Url erweitert

---

src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java

Fixes #301 
Hat bei meinen Tests funktioniert, schadet aber sicherlich nicht, vor dem Merge auch auf den Servern mal zu testen.

Fix ErrorCode 429

---

src/main/java/mServer/crawler/sender/MediathekArd.java

Fix Ermittlung der Dauer eines Films

---

src/main/java/mServer/crawler/sender/MediathekNdr.java

Untertitel auslesen wenn Titel und Thema gleich sind

---

src/main/java/mServer/crawler/sender/orf/tasks/OrfFilmDetailTask.java

Fixed wrong adding of small url.

Fix for #362

---

src/main/java/mServer/crawler/sender/hr/HrSendungDeserializer.java
src/test/developTest/java/mServer/crawler/sender/hr/HrSendungDeserializerTest.java
src/test/developTest/resources/hr/hr_sendung_detail3.html

HR: Fix Ermittlung Video-URL

---

src/main/java/mServer/crawler/sender/orf/OrfConstants.java
src/main/java/mServer/crawler/sender/orf/parser/OrfVideoDetailDeserializer.java

Behebt die HTTPS Fehler aus #373 durch Ergänzen von ".sf" in der URL wenn nötig.

Fixes #373

---

src/main/java/mServer/crawler/sender/MediathekReader.java

Fixes #381 
Anmerkung: die Änderung ist nur in Methode processOrf, Rest ist Formatierung

ORF: Geo-Urls angepasst

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

URL für Subcategories angepasst

---

src/main/java/mServer/crawler/sender/phoenix/parser/ZdfDownloadDtoDeserializer.java
src/main/java/mServer/crawler/sender/phoenix/tasks/PhoenixFilmDetailTask.java

Fix Verarbeitung GeoLocations

---

src/main/java/mServer/crawler/sender/MediathekZdf.java

ZDF: Fix Dateigröße in Filmliste

---

src/main/java/mServer/crawler/sender/MediathekZdf.java

Fixing #379

---

src/main/java/mServer/crawler/sender/MediathekRbb.java

RBB: Umstellung VideoUrl-Ermittlung auf allgemeine ARD-Logik

---

src/main/java/mServer/crawler/sender/newsearch/ZDFSearchTask.java

Ein schneller Workaround, damit zumindest Filme, die in der Vergangenheit ausgestrahlt wurden, wieder gefunden werden. Der finale Fix wird aufwändiger werden.

ZDF: Quickfix - Reduktion des Suchzeitraums

---

build.gradle
src/main/java/mServer/crawler/sender/newsearch/ZdfIndexPageDeserializer.java
src/test/developTest/java/mServer/crawler/sender/newsearch/ZdfIndexPageDeserializerTest.java

ZDF: Umstellung Tokenermittlung

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

ARTE: Tagesprogramm in der Zukunft durchsuchen

---

src/main/java/mServer/crawler/sender/newsearch/ZDFClient.java
src/main/java/mServer/crawler/sender/newsearch/ZDFEntryDTODeserializer.java

ZDF: Retry für Suchanfragen, wenn sie mit 403 scheitern

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

Arte: weitere Kategorien hinzugefügt

---

src/main/java/mServer/crawler/sender/orf/tasks/OrfDayTask.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfFilmDetailTask.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfHelper.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfLetterPageTask.java

Anpassungen an neues Design der ORF-Mediathek (#465)

ORF: Anpassungen an neues Design

---

src/main/java/mServer/crawler/sender/phoenix/tasks/PhoenixOverviewTask.java

PHÖNIX: Workaround für Paging-Problem bei Phönix

---

src/main/java/mServer/crawler/sender/MediathekKika.java

KIKA: Fix HD-Videos

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

weitere Kategorien für ARTE Concerts

---

src/main/java/mServer/crawler/sender/ard/ArdCrawler.java

ARD: Suchzeitraum wegen Laufzeitproblemen reduziert

---

build.gradle
src/main/java/mServer/crawler/AddToFilmlist.java

Fixes #492 
@alex1702 Zusätzlich muss noch die MLib-Version aktualisiert werden, wenn eine Version mit https://github.com/mediathekview/MLib/pull/111 in MLib erstellt ist.

Anpassung an neue okhttp3-Version

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

ARTE: Fix Subcategory-URL

---

src/main/java/mServer/crawler/sender/hr/HrSendungDeserializer.java
src/test/developTest/java/mServer/crawler/sender/hr/HrSendungDeserializerTest.java
src/test/developTest/resources/hr/hr_sendung_detail1.html
src/test/developTest/resources/hr/hr_sendung_detail2.html

HR: Fix Video-Erkennung

---

src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

Logging erweitert für Analyse der ARTE-Läufe auf den Servern.

ARTE Logging

---

src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

Arte analyze

---

src/main/java/mServer/crawler/sender/newsearch/ZDFVideoDTODeserializer.java

3sat/ZDF: Fix <br>-Tag in Titel

---

src/main/java/mServer/crawler/sender/arte/ArteDatenFilmDeserializer.java
src/main/java/mServer/crawler/sender/arte/ArteJsonObjectToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDTO.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDeserializer.java
src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

ARTE: Hörfassungen

---

src/main/java/mServer/crawler/sender/br/BrSendungsFolgenTask.java

BR: Fix unknown operator

---

src/main/java/mServer/crawler/sender/arte/ArteVideoDeserializer.java

ARTE: Dauer wieder füllen

---

src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java

SRF: Fix NullPointerException für Geo-Blocking

---

src/main/java/mServer/crawler/sender/orf/tasks/OrfFilmDetailTask.java

ORF: Fix Titel+Beschreibung

---

src/main/java/mServer/crawler/sender/AbstractMediathekZdf.java

ZDF: Erweiterung URL-Optimierung

---

src/main/java/mServer/crawler/sender/ard/json/ArdVideoInfoJsonDeserializer.java
src/main/java/mServer/crawler/sender/base/M3U8Dto.java
src/main/java/mServer/crawler/sender/base/UrlUtils.java

ARD: Fix Alpha Centauri URLs

---

src/main/java/mServer/crawler/sender/ard/json/ArdFilmDeserializer.java

ARD: Fix film without show element

---

src/main/java/mServer/crawler/sender/ard/ArdCrawler.java
src/main/java/mServer/crawler/sender/ard/json/ArdFilmDeserializer.java

added Radio Bremen TV

---

src/main/java/mServer/crawler/sender/ard/ArdFilmUrlInfoDto.java
src/main/java/mServer/crawler/sender/ard/json/ArdMediaArrayToDownloadUrlsConverter.java
src/main/java/mServer/crawler/sender/ard/json/ArdVideoInfoJsonDeserializer.java

ARD: supports FullHD

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

ARTE: Ignore subpages of subcategories, only parse the first 100 films

---

src/main/java/mServer/crawler/sender/ard/ArdCrawler.java

ARD: search subsenders

---

src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java

SRF: added new parser of subtitle

---

build.gradle
src/main/java/mServer/crawler/sender/orf/parser/OrfVideoDetailDeserializer.java

ORF: ignore quality Q8A

---

build.gradle
src/main/resources/log4j2.xml

Detaillogging für ORF deaktiviert, nachdem Problem behoben ist.

OrfLogger: increased log level to error

---

build.gradle
src/main/java/mServer/crawler/sender/MediathekReader.java

additional SWR Geo-Url

---

src/main/java/mServer/crawler/sender/dreisat/DreiSatCrawler.java
src/main/java/mServer/crawler/sender/dreisat/DreisatConstants.java
src/main/java/mServer/crawler/sender/dreisat/DreisatDayPageHtmlDeserializer.java
src/main/java/mServer/crawler/sender/dreisat/DreisatDayPageHtmlTask.java

#595 3Sat html day pages

---

src/main/java/mServer/crawler/sender/MediathekReader.java

add rbb geo location url

---

src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java

#601: replace cc license in title

---

build.gradle
src/main/java/mServer/crawler/sender/br/BrCrawler.java
src/main/java/mServer/crawler/sender/br/BrMissedSendungsFolgenDeserializer.java
src/main/java/mServer/crawler/sender/br/BrMissedSendungsFolgenTask.java
src/main/java/mServer/crawler/sender/br/Consts.java
src/main/java/mServer/crawler/sender/br/WebAccessHelper.java

Fix für #602, bin gespannt, ob es schon ausreicht...

#602: Fix MissedSendungsFolgenTask und Umstellung auf neue BR-Url

---

dist/live-streams.json

Updated live-stream urls like described in https://forum.mediathekview.de/topic/3525/livestream-3sat-zdf-neo-info-phoenix-urls-haben-sich-ge%C3%A4ndert

Updated live-stream urls

---

src/main/java/mServer/crawler/sender/srf/SrfConstants.java
src/main/java/mServer/crawler/sender/srf/tasks/SrfTopicsOverviewTask.java

srf added sport-clip

---

README.md
src/main/java/mServer/crawler/sender/MediathekHr.java
src/main/java/mServer/crawler/sender/ard/tasks/ArdTaskBase.java
src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java
src/main/java/mServer/crawler/sender/base/AbstractUrlTask.java
src/main/java/mServer/crawler/sender/hr/HrSendungOverviewCallable.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfTaskBase.java
src/main/java/mServer/crawler/sender/wdr/WdrUrlLoader.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfTaskBase.java

* docu crawler
* fix crawler statistics

Statistics fix

---

src/main/java/mServer/crawler/sender/ard/json/ArdMediaArrayToDownloadUrlsConverter.java
src/main/java/mServer/crawler/sender/base/UrlUtils.java
src/main/java/mServer/crawler/sender/orf/parser/OrfVideoDetailDeserializer.java

#622 remove query parameter from film url

---

src/main/java/mServer/crawler/sender/sr/tasks/SrFilmDetailTask.java

#625 set website url

---

build.gradle
src/main/java/mServer/crawler/sender/ard/json/ArdMediaArrayToDownloadUrlsConverter.java
src/main/java/mServer/crawler/sender/sr/tasks/SrFilmDetailTask.java

#624 ignore f4m files

---

src/main/java/de/mediathekview/mserver/crawler/basic/AbstractJsonRestTask.java
src/main/java/de/mediathekview/mserver/crawler/basic/FilmInfoDto.java
src/main/java/de/mediathekview/mserver/crawler/funk/json/AbstractFunkElementDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/funk/json/NexxCloudVideoDetailsDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/funk/tasks/FunkVideosToFilmsTask.java

Fixing the funk crawler

---

src/main/java/de/mediathekview/mserver/crawler/basic/AbstractCrawler.java

Siehe PR für MLIB. Wenn der Crawler über Miternacht läuft gibt es eine Exception.

fix exception when start and end time are on different days

---

build.gradle
src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java

trim whitespaces in titleElement if subtitle is added

---

build.gradle
src/main/java/mServer/crawler/sender/ard/ArdCrawler.java

#667
@alex1702 je nachdem, wann du das Problem korrigieren kannst, musst du unter Umständen andere Tage nochmal laufen lassen und den PR noch anpassen.

rerun missing ARD days

---

src/main/java/mServer/crawler/AddToFilmlist.java

added logs to analyze issue #663

added logs to analzye issue

---

build.gradle
src/main/java/mServer/crawler/sender/br/BrFilmDeserializer.java

fixes ClassCastExceptions in BR-Crawler.

BR fix ClassCastException

---

build.gradle
src/main/java/mServer/crawler/AddToFilmlist.java

fix remove offline orf films

---

src/main/java/mServer/crawler/AddToFilmlist.java

bugfix for PR #678 and issue #676

bugfix 676

---

build.gradle
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfTaskBase.java

ZDF Rate limiting

---

src/main/java/de/mediathekview/mserver/crawler/funk/tasks/FunkVideosToFilmsTask.java
src/main/java/de/mediathekview/mserver/crawler/zdf/DownloadDtoFilmConverter.java
src/main/java/de/mediathekview/mserver/crawler/zdf/ZdfVideoUrlOptimizer.java

Beim ZDF kommt es vor, dass Film nur ein Video mit SMALL haben.
In diesem Fall kommt es dann zu einem Nullpointer beim toString.

Develop zdf Nullpointer für Filme mit kleiner Auflösung

---

build.gradle
src/main/java/mServer/crawler/sender/ard/ArdCrawler.java

recrawl ard days

---

src/main/java/de/mediathekview/mserver/crawler/orf/OrfVideoInfoDTO.java
src/test/java/de/mediathekview/mserver/crawler/orf/tasks/OrfFilmDetailTaskJugendschutzTest.java
src/test/resources/orf/orf_film_jugendschutz.html

remove orf Jugendschutz entries

---

src/main/java/mServer/crawler/sender/srf/SrfConstants.java

search inactive shows

---

build.gradle
src/main/java/mServer/crawler/sender/MediathekHr.java
src/main/java/mServer/crawler/sender/hr/HrSendungOverviewCallable.java

- entfernt eine nicht benötigte dependency, da über Mlib vorhanden
- nutzt OkHttpClient Instanz anstatt Jsoup.connect -> verbessertes und robusteres connection handling
@pidoubleyou Wohin wird der Output von LOG.error geschrieben? Konnte da kein logfile in den Verzeichnissen zu finden.

HR crawler enhancements

---

build.gradle
src/main/java/mServer/crawler/AddToFilmlist.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfHelper.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

adjust pattern to remove time from topic

---

src/main/java/mServer/crawler/sender/ard/ArdConstants.java

fix ard website url

---

src/main/java/mServer/crawler/sender/ard/json/ArdMediaArrayToDownloadUrlsConverter.java

add https if protocol is missing in video url

---

src/main/java/mServer/crawler/AddToFilmlist.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

update ARD website in old films

---

src/main/java/de/mediathekview/mserver/base/utils/UrlUtils.java
src/main/java/de/mediathekview/mserver/base/webaccess/JsoupConnection.java
src/main/java/de/mediathekview/mserver/crawler/ard/ArdUrlOptimizer.java
src/main/java/de/mediathekview/mserver/crawler/ard/json/ArdFilmDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/ard/json/ArdMediaArrayToDownloadUrlsConverter.java
src/main/java/de/mediathekview/mserver/crawler/ard/json/ArdVideoInfoJsonDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/arte/tasks/ArteFilmTask.java
src/main/java/de/mediathekview/mserver/crawler/basic/AbstractCrawler.java
src/main/java/de/mediathekview/mserver/crawler/dw/parser/DWDownloadUrlsParser.java
src/main/java/de/mediathekview/mserver/crawler/dw/tasks/DWFilmDetailsTask.java
src/main/java/de/mediathekview/mserver/crawler/hr/tasks/HrSendungenOverviewPageTask.java
src/main/java/de/mediathekview/mserver/crawler/hr/tasks/HrSendungsfolgedetailsTask.java
src/main/java/de/mediathekview/mserver/crawler/orf/tasks/OrfFilmDetailTask.java
src/main/java/de/mediathekview/mserver/crawler/phoenix/tasks/PhoenixFilmDetailTask.java
src/main/java/de/mediathekview/mserver/crawler/sr/tasks/SrFilmDetailTask.java
src/main/java/de/mediathekview/mserver/crawler/srf/parser/SrfFilmJsonDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/zdf/DownloadDtoFilmConverter.java
src/main/java/de/mediathekview/mserver/crawler/zdf/ZdfVideoUrlOptimizer.java
src/main/java/de/mediathekview/mserver/crawler/zdf/tasks/ZdfFilmDetailTask.java
src/test/java/de/mediathekview/mserver/crawler/swr/SwrUrlOptimizerTest.java
src/test/java/de/mediathekview/mserver/crawler/zdf/ZdfVideoUrlOptimizerTest.java

Move all OKHTTP releated function into JsoupConnection class  and provide convenient method in abstractCrawler
PR for issue #715

Feature/715 - Jsoup connections

---

MServer-Config.yaml
src/main/java/de/mediathekview/mserver/base/config/MServerBasicConfigDTO.java
src/main/java/de/mediathekview/mserver/crawler/ard/ArdCrawler.java
src/main/java/de/mediathekview/mserver/crawler/arte/ArteCrawler.java
src/main/java/de/mediathekview/mserver/crawler/funk/FunkCrawler.java
src/main/java/de/mediathekview/mserver/crawler/hr/HrCrawler.java
src/main/java/de/mediathekview/mserver/crawler/kika/KikaCrawler.java
src/main/java/de/mediathekview/mserver/crawler/orf/OrfCrawler.java
src/main/java/de/mediathekview/mserver/crawler/phoenix/PhoenixCrawler.java
src/main/java/de/mediathekview/mserver/crawler/sr/SrCrawler.java
src/main/java/de/mediathekview/mserver/crawler/srf/SrfCrawler.java
src/test/resources/MServer-JUnit-Config.yaml

dis-/enable topics search

---

src/main/java/mServer/crawler/sender/phoenix/PhoenixConstants.java
src/main/java/mServer/crawler/sender/phoenix/PhoenixCrawler.java
src/main/java/mServer/crawler/sender/phoenix/tasks/PhoenixFilmDetailTask.java
src/main/java/mServer/crawler/sender/phoenix/tasks/PhoenixOverviewTask.java
src/main/java/mServer/crawler/sender/zdf/json/DownloadDto.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfDownloadDtoDeserializer.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfFilmDetailTask.java

fix Phoenix crawler

---

src/main/java/mServer/crawler/sender/ard/ArdConstants.java

add Phoenix+Funk clients

---

build.gradle
src/main/java/mServer/crawler/sender/MediathekReader.java

improve ard geolocation guessing

---

build.gradle
src/main/java/mServer/crawler/sender/MediathekReader.java

set geolocation of ARTE entries in ARD Mediathek

---

build.gradle
src/main/java/mServer/crawler/AddToFilmlist.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

orf: remove geoprotection redirect

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

arte: fix subcategory url

---

src/main/java/mServer/crawler/sender/phoenix/parser/PhoenixFilmDetailDeserializer.java

#775 phoenix: fix basename not available anymore

---

src/main/java/mServer/crawler/sender/kika/KikaCrawler.java
src/main/java/mServer/crawler/sender/kika/tasks/KikaTopicOverviewPageTask.java

Abhilfe für https://forum.mediathekview.de/topic/4480/bernd-das-brot-fehlt

kika: additional topic pages

---

src/main/java/mServer/crawler/sender/arte/MediathekArte.java

arte: add ARTE.ES

---

src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDTO.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDeserializer.java
src/main/java/mServer/crawler/sender/arte/ArteVideoType.java
src/main/java/mServer/crawler/sender/arte/ArteVideoTypeMapper.java
src/main/java/mServer/crawler/sender/arte/MediathekArte.java

Anpassung der Bezeichnung der Filme für verschiedene Sprachen + Unterstützung Originalversion (siehe auch #758)

arte: refactor video deserialization

---

build.gradle
src/main/java/mServer/crawler/sender/arte/MediathekArte.java

ARTE: fix multithreading bug and add IT+PL

---

src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDetailsDTO.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDetailsDeserializer.java

arte: fix missing duration

---

src/main/java/mServer/crawler/sender/arte/ArteVideoTypeMapper.java

ARTE.DE: fix VOF-STA

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDTO.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDeserializer.java

ARTE: fix trailer duration

---

src/main/java/mServer/crawler/sender/ard/json/ArdVideoInfoJsonDeserializer.java
src/main/java/mServer/crawler/sender/base/M3U8Dto.java
src/main/java/mServer/crawler/sender/base/M3U8Parser.java

fix ard funk: m3u8 files containing relative urls

---

src/main/java/mServer/crawler/sender/orf/parser/OrfVideoDetailDeserializer.java

ORF: ignore QXADRM and QXBDRM to reduce logs

ignore QXADRM and QXBDRM

---

src/main/java/mServer/crawler/sender/ard/tasks/ArdTaskBase.java
src/main/java/mServer/crawler/sender/base/AbstractDocumentTask.java

additional logs to analyze socket timeouts

---

src/main/java/mServer/crawler/sender/zdf/parser/ZdfTopicPageHtmlDeserializer.java

ZDF: fix lazyload of teasers

---

src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java

SRF: fix videoUrl contains only filename

---

build.gradle
src/main/java/mServer/crawler/sender/base/M3U8Parser.java
src/main/java/mServer/crawler/sender/base/UrlUtils.java
src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java

#812 fix another srf filename in m3u8

---

build.gradle
src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java

#812 remove drm videos

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/main/java/mServer/crawler/sender/arte/ArteVideoDeserializer.java
src/main/java/mServer/crawler/sender/arte/MediathekArte.java

fix arte removed api /v1/config

---

src/main/java/de/mediathekview/mserver/crawler/funk/json/NexxCloudVideoDetailsDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/funk/json/NexxResolutionDTO.java

Funk: fix NumberFormatException

---

build.gradle
src/main/java/mServer/crawler/sender/funk/json/NexxCloudVideoDetailsDeserializer.java
src/main/java/mServer/crawler/sender/funk/json/NexxResolutionDTO.java

#829 fix NumberFormatException

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteCategoryFilmListDeserializer.java
src/main/java/mServer/crawler/sender/arte/ArteCategoryFilmsDTO.java
src/main/java/mServer/crawler/sender/arte/ArteCollectionDeserializer.java
src/main/java/mServer/crawler/sender/arte/MediathekArte.java

ARTE: handle Collections in CategoryFilmList

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteCategoryFilmListDeserializer.java
src/main/java/mServer/crawler/sender/arte/ArteCollectionChildDeserializer.java
src/main/java/mServer/crawler/sender/arte/ArteCollectionParentDeserializer.java
src/main/java/mServer/crawler/sender/arte/MediathekArte.java

ARTE: fix collections with multiple children

---

src/main/java/mServer/crawler/sender/ard/json/ArdMediaArrayToDownloadUrlsConverter.java
src/main/java/mServer/crawler/sender/base/Qualities.java

ard: ignore uhd urls

---

src/main/java/mServer/crawler/sender/zdf/ZdfConstants.java
src/main/java/mServer/crawler/sender/zdf/ZdfFilmDto.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfDownloadDtoDeserializer.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfFilmDetailTask.java

zdf added support of sign language videos

---

pom.xml
src/test/java/de/mediathekview/mserver/crawler/br/BrGraphQLQueriesTest.java
src/test/java/de/mediathekview/mserver/crawler/br/data/BrClipTypeTest.java
src/test/java/de/mediathekview/mserver/crawler/br/data/BrIDTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/GsonGraphQLHelperTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/variables/BooleanVariableTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/variables/FloatVariableTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/variables/IntegerVariableTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/variables/RecursiveAbstractVariableTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/variables/StringVariableTest.java
src/test/java/de/mediathekview/mserver/crawler/br/graphql/variables/VariableListTest.java
src/test/java/de/mediathekview/mserver/crawler/br/tasks/BrBroadcastsTaskTest.java
src/test/java/de/mediathekview/mserver/crawler/br/tasks/BrGetClipDetailsTaskTest.java
src/test/java/de/mediathekview/mserver/crawler/br/tasks/BrTaskTestBase.java
src/test/java/de/mediathekview/mserver/testhelper/WireMockTestBaseJUnit5.java

Updated existing Tests to JUnit5 with AssertJ

Updated BR Unit Tests to JUnit5 with AssertJ

---

src/test/java/de/mediathekview/mserver/crawler/swr/SwrUrlOptimizerTest.java

Improve SWR Test by updating to JUnit5 and using assertJ for assertions

[Improve] Updated SWR Test to JUnit5

---

src/test/java/de/mediathekview/mserver/crawler/dreisat/DreisatDayPageHtmlDeserializerTest.java
src/test/resources/dreisat/dreisat_page_second_day.html

I improved the Dreisat test by adding a second test and upgrading/updating it to Junit5 so i can get Hacktober done.

[Improve] Updated Dreisat test To Junit5

---

src/test/java/de/mediathekview/mserver/crawler/funk/FunkChannelDeserializerTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/FunkChannelsRestTaskTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/FunkTaskTestBase.java
src/test/java/de/mediathekview/mserver/crawler/funk/FunkVideoDeserializerTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/FunkVideoRestTaskTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/FunkVideosToFilmsTaskTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/NexxCloudSessionInitDeserializerTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/NexxCloudSessionInitiationTaskTest.java
src/test/java/de/mediathekview/mserver/crawler/funk/NexxCloudVideoDetailsDeserializerTest.java

Updated all Tests to JUnit5 with AssertJ as AssertionFramework

Updated Funk Unit Tests to JUnit5 with AssertJ

---

src/main/java/de/mediathekview/mserver/crawler/kika/KikaApiConstants.java
src/main/java/de/mediathekview/mserver/crawler/kika/json/KikaApiTopicPageDeserializer.java

Website in original data may point to topic rather than individual video.

reconstruct website for all entries

---

src/main/java/mServer/crawler/sender/phoenix/parser/PhoenixFilmDetailDeserializer.java
src/main/java/mServer/crawler/sender/phoenix/tasks/PhoenixFilmDetailTask.java

Phoenix: fix missing title

---

build.gradle
src/main/java/mServer/crawler/sender/zdf/ZdfVideoUrlOptimizer.java

zdf: fix missing hd urls

---

src/main/java/mServer/crawler/sender/kika/tasks/KikaApiFilmTask.java

add Ratelimiter

---

src/main/java/mServer/crawler/sender/base/JsonUtils.java
src/main/java/mServer/crawler/sender/zdf/DownloadDtoFilmConverter.java
src/main/java/mServer/crawler/sender/zdf/ZdfVideoUrlOptimizer.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfDownloadDtoDeserializer.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java

zdf: use android_native_5

---

src/main/java/mServer/crawler/sender/orf/OrfCrawler.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfHistoryOverviewTask.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfHistoryTopicTask.java

ORF: add history

---

src/main/java/de/mediathekview/mserver/crawler/zdf/json/DownloadDto.java
src/main/java/de/mediathekview/mserver/crawler/zdf/json/ZdfDownloadDtoDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/zdf/tasks/ZdfFilmDetailTask.java
src/test/java/de/mediathekview/mserver/crawler/zdf/json/ZdfDownloadDtoDeserializerTest.java
src/test/java/de/mediathekview/mserver/crawler/zdf/tasks/ZdfFilmDetailTaskMultipleLanguagesTest.java
src/test/resources/zdf/zdf_video_details_eng_ut.json

add language specific subtitle urls

---

src/main/java/mServer/crawler/AddToFilmlist.java

fix: film is added to film list if online check throws exception

---

build.gradle
src/main/java/mServer/crawler/sender/ard/tasks/ArdTopicPageTask.java

https://forum.mediathekview.de/topic/5165/ard-die-jungen-%C3%A4rzte-folgen-300-312
https://forum.mediathekview.de/topic/5183/unter-unserem-himmel-der-forggensee/1

load all entries of two topics temporarily

---

build.gradle
src/main/java/mServer/crawler/sender/kika/json/KikaApiTopicPageDeserializer.java

backport dev for reconstruct url issue 893

---

MServer-Config.yaml
src/main/java/de/mediathekview/mserver/base/config/MServerConfigDTO.java
src/main/java/de/mediathekview/mserver/crawler/CrawlerManager.java
src/main/java/de/mediathekview/mserver/crawler/basic/IgnoreFilmFilter.java
src/main/java/de/mediathekview/mserver/ui/config/MServerConfigUI.java
src/main/resources/MServer-Config.yaml
src/main/resources/ignoreFilmlist.txt
src/test/java/de/mediathekview/mserver/crawler/basic/IgnoreFilmFilterTest.java
src/test/resources/ignoreFilmlist.txt

Java class to Filter film by title (remove from filmlist)
Add config parameter
Add filter hook
unit test

add ignoreFilmFilter

---

src/main/java/mServer/crawler/sender/arte/ArteCategoryFilmListDeserializer.java
src/main/java/mServer/crawler/sender/arte/ArteCategoryFilmsDTO.java
src/main/java/mServer/crawler/sender/arte/MediathekArte.java
src/test/developTest/java/mServer/crawler/sender/arte/ArteCategoryFilmListDeserializerTest.java

reactivate ARTE.FR

---

src/test/java/de/mediathekview/mserver/crawler/kika/tasks/KikaApiTopicDeserializerTest.java
src/test/java/de/mediathekview/mserver/crawler/kika/tasks/KikaApiVideoInfoDeserializerTest.java

Improved the Kika tests by updating them to JUnit5.

Kika: Update to Junit5

---

src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java

SRF remove changing url parameters in m3u8 files

---

README.md

update crawler overview

---

src/main/java/mServer/crawler/AddToFilmlist.java
src/main/java/mServer/crawler/sender/ard/json/ArdTopicsOverviewDeserializer.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

ARD: ignore ZDF/3sat/ARTE/KIKA entries

---

src/main/java/mServer/crawler/sender/ard/ArdUrlOptimizer.java

optimize wdr hd urls

---

build.gradle
src/main/java/mServer/crawler/sender/orf/OrfCrawler.java
src/main/java/mServer/crawler/sender/orf/json/OrfMoreEpisodesDeserializer.java
src/main/java/mServer/crawler/sender/orf/parser/OrfMoreEpisodesParser.java
src/main/java/mServer/crawler/sender/orf/tasks/OrfFilmDetailTask.java

ORF: extend topic search

---

src/main/java/mServer/crawler/sender/zdf/AbstractZdfCrawler.java
src/main/java/mServer/crawler/sender/zdf/parser/ZdfTopicsPageHtmlDeserializer.java

ZDF: optimize runtime

---

build.gradle
src/main/java/mServer/crawler/sender/orfon/json/OrfOnEpisodeDeserializer.java

remove orf dummy urls

---

src/main/java/mServer/crawler/sender/orfon/json/OrfOnEpisodeDeserializer.java

ORF add parsevideofromthumbnail

---

src/main/java/de/mediathekview/mserver/base/utils/JsonUtils.java
src/main/java/de/mediathekview/mserver/crawler/zdf/json/ZdfFilmDetailDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/zdf/parser/ZdfTopicsPageHtmlDeserializer.java
src/test/java/de/mediathekview/mserver/crawler/zdf/json/ZdfFilmDetailDeserializerTest.java
src/test/resources/zdf/zdf_film_details_with_episodes.json

Add season and episode to title of ZDF films.
It will be added as " (S<>E<>)" at the end of the title

ZDF add episode to title

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java

fix arte crawler

---

build.gradle
src/main/java/mServer/crawler/sender/ard/ArdConstants.java
src/main/java/mServer/crawler/sender/ard/ArdCrawler.java
src/main/java/mServer/crawler/sender/ard/json/ArdDayPageDeserializer.java

ard: new day page url

---

build.gradle
src/main/java/mServer/crawler/AddToFilmlist.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

fix trailing dash in title

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteListBaseDeserializer.java

ARTE: fix host in next pages

---

build.gradle
src/main/java/mServer/crawler/sender/zdf/ZdfVideoUrlOptimizer.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfDownloadDtoDeserializer.java

zdf: 720p als normale Url analog ARD

---

build.gradle
src/main/java/mServer/crawler/FilmeSuchen.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

fix zdf duplicates

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/MediathekArte.java

Arte: reduce search depth

---

src/main/java/mServer/crawler/AddToFilmlist.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

update thema with bindestrich

---

src/main/java/de/mediathekview/mserver/crawler/orfon/json/OrfOnEpisodeDeserializer.java

add all urls to default allocation instead of first found

---

src/main/java/mServer/crawler/AddToFilmlist.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

title: rename (deu-ad) to (audiodescription)

---

src/main/java/mServer/crawler/sender/ard/json/ArdFilmDeserializer.java

Bugfix/ard1047
create a OV film from video data if present.
See #1047

ARD OV videos missing (master)

---

build.gradle
src/main/java/mServer/crawler/sender/kika/tasks/KikaApiFilmTask.java

WDR Urls are already highest quality and must not be optimized.
Quickfix - do not optimize WDR urls
see #1055

Kika incorrect HD Url

---

src/main/java/de/mediathekview/mserver/crawler/ard/json/ArdFilmDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/ard/json/ArdVideoInfoDto.java
src/main/java/de/mediathekview/mserver/crawler/ard/json/ArdVideoInfoJsonDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/sr/tasks/SrFilmDetailTask.java
src/test/java/de/mediathekview/mserver/crawler/ard/json/ArdFilmDeserializerTest.java

feature/ard1047
create a OV film from video data if present.
See https://github.com/mediathekview/MServer/issues/1047

ARD OV videos missing (dev)

---

src/main/java/mServer/crawler/sender/orfon/OrfOnVideoInfoDTO.java
src/main/java/mServer/crawler/sender/orfon/json/OrfOnEpisodeDeserializer.java
src/main/java/mServer/crawler/sender/orfon/task/OrfOnEpisodeTask.java

Add filter for protected ORF videos see #1064

remove protected videos

---

src/main/java/mServer/crawler/sender/ard/tasks/ArdTopicPageTask.java

https://forum.mediathekview.de/topic/6460/mit-mut-m%C3%B6rtel-und-ohne-millionen-folgen-1-2-3-4-und-6-fehlen

ard: deep search for Nordstory

---

src/main/java/mServer/crawler/sender/dreisat/AbstractZdfCrawler.java
src/main/java/mServer/crawler/sender/dreisat/DreisatConstants.java
src/main/java/mServer/crawler/sender/phoenix/PhoenixConstants.java
src/main/java/mServer/crawler/sender/phoenix/tasks/PhoenixFilmDetailTask.java
src/main/java/mServer/crawler/sender/zdf/ZdfCrawler.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfFilmDetailTask.java

3Sat/ZDF: fix default sender
