src/main/java/mServer/crawler/sender/MediathekArd.java

Die fehlende Sendung  für #97 wurde via. "Film & Serie @ One" in der Mediathek gelistet. Die einzige Qualität die gelistet wurde konnte nicht gefunden werden da bisher m3u8 Datein mit der Qualität "auto" nicht beachtet wurden. Ich habe dem ARD Crawler entsprechend das Pattern für diese Sendungen beigebracht.
Die Filmliste enthält nun, wenn ich das beim Testen richtig gesehen habe, einige Sendungen und Filme mehr.
@xaverW Wurden diese Sendungen bisher absichtlich weg gelassen?
Hier eine mit der Änderung erzeugte ARD-Filmliste: https://p.elaon.de/qm0/

Fixing #97

---

build.gradle
src/main/java/mServer/tool/MserverDaten.java

Funktionsaufruf ausgetauscht. Benötigt zwingend die neue MSearch Version, also noch nicht mergen.

Feature/neue MSearch anpassung

---

src/main/java/mServer/crawler/sender/newsearch/ZDFEntryDTODeserializer.java
src/main/java/mServer/crawler/sender/newsearch/ZDFEntryTask.java
src/main/java/mServer/crawler/sender/newsearch/ZDFSearchTask.java
src/main/resources/log4j2.xml

Fixed #117 
Some ZDF API results don't contain the "mainVideoElement" and co directly. They have an extra element named "http://zdf.de/rels/content/video-page-teaser". This extra element contains the mainVideoElement and the URLs with further informations. 
The crawler now tests if the mainVidoeElement is directly available, if its not it will try to find it under the extra element.
Btw. I also added Log4J with some debug messages for the crawler and a log4j2.xml.

Fixed #117

---

src/main/java/mServer/crawler/sender/MediathekZdf.java

ZDF-Crawler beendet sich wieder korrekt

Action an Phaser deregistrieren, damit Phaser auch beendet wird

---

src/main/java/mServer/crawler/sender/Mediathek3Sat.java

Fixes #137 
Aus den Links für Unterseiten/Filme ist "http:" in der Mediathek entfallen

Anpassung der Link/Video-Suche an Mediathek

---

src/main/java/mServer/crawler/AddToFilmlist.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

Fix für #142, Details zu der Ursache des Problems sind darin beschrieben.
Bei meinen Tests haben sich keine messbaren Performanceunterschiede gezeigt.

Fix für doppelte Einträge in Ergebnisliste

---

src/main/java/mServer/crawler/sender/MediathekZdfTivi.java

ns3:duration nicht mehr verwendet, da dies die Länge des Teasers
beinhaltet. Stattdessen duration oder lengthSec verwendet.
Fixes #189

Fix Längenermittlung

---

src/main/java/mServer/tool/M3U8Utils.java

[DE]
Das WDR nutzt eine neue URL & die Region `weltweit` wird bei der Domain mit `ww` abgekürzt. Durch diesen Fix wird bei der neuen und alten URL versucht eine MP4 zu finden und die Region `weltweit` wird nun unterstüztz.
[EN]
The WDR uses now a new URL an the region `weltweit` is shortenend by `ww` for the domain. This fix now supports the old and the new URL beside the region `weltweit` is now supported.

Added new url and exta logic for region `weltweit`

---

src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

Fix für #225: ExecutorService nur noch einmal für CategoryLoader erzeugen und am Ende wieder beenden, damit keine Threads mehr übrig bleiben

Fix: Threads in ExecutorService explizit beenden

---

src/main/java/mServer/crawler/sender/MediathekArd.java

Behebt das Problem für #306 mit den falschen Minutenangaben.
Ein merge nach develop ist nicht notwendig da der neue ARD crawler hier bereits richtig agiert.

Fixed #306

---

src/main/java/mServer/crawler/sender/MediathekNdr.java

NDR leitet alle http-Anfragen auf https um
Deshalb ist der Download der Untertitel mit http nicht mehr möglich.
Fixes #333

NDR-Urls auf https umgestellt

---

src/main/java/mServer/crawler/sender/MediathekArd.java

ARD: Fix für Untertitel-URLs

---

src/main/java/mServer/crawler/sender/newsearch/ZDFSearchTask.java

Suchzeitraum für Zukunft erweitert auf zwei Monate auf Wunsch aus Forum. Tests haben keine signifikante Erhöhung der Crawlerlaufzeit insgesamt ergeben.

ZDF: Suchzeitraum für Zukunft erweitert

---

src/main/java/mServer/crawler/sender/orf/OrfVideoInfoDTO.java
src/main/java/mServer/crawler/sender/orf/parser/OrfVideoDetailDeserializer.java

QuickFix, so dass ORF-Crawler den Suchlauf nicht mehr blockiert. Er findet jetzt zwar keine Filme mehr, aber erstmal egal.

ORF: VideoInfoDTO nur zurückgeben, wenn auch Video-URLs vorhanden sind

---

src/main/java/mServer/crawler/sender/newsearch/ZDFConfigurationLoader.java

Fallbacktoken aktualisiert, so dass erstmal Filme gefunden werden. Die Logik zur Ermittlung des Tokens muss dennoch korrigiert, damit die Lösung längerfristig funktioniert.

ZDF: Quickfix für geänderte Tokenlogik

---

src/main/java/mServer/crawler/sender/MediathekZdf.java
src/main/java/mServer/crawler/sender/newsearch/ZDFEntryTask.java

unnötige NullPointerException abgefangen und Logausgabe erweitert.
Ziel: weitere Analyse von diesem [Problem](https://forum.mediathekview.de/topic/2128/zdf-erst-ab-11-uhr-vorhanden)

ZDF Log+Fehlerhandling erweitert

---

src/main/java/mServer/crawler/sender/arte/ArteHttpClient.java
src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java

weitere Analysen: Crawler führt für Analyse nur noch Testrequests durch

ARTE: Testrequests für Analyse

---

src/main/java/de/mediathekview/mserver/crawler/kika/tasks/KikaFilmUrlInfoDto.java
src/main/java/de/mediathekview/mserver/crawler/kika/tasks/KikaLetterPageTask.java
src/main/java/de/mediathekview/mserver/crawler/kika/tasks/KikaSendungsfolgeVideoDetailsTask.java
src/main/java/de/mediathekview/mserver/crawler/kika/tasks/KikaTopicLandingPageTask.java
src/main/java/de/mediathekview/mserver/crawler/kika/tasks/KikaTopicOverviewPageTask.java

Filesize aus den Filmdaten überenehmen
Die Dauer ist in einigen Fällen in DURATION leer aber das LENGTH Element ist gesetzt
Die Selectoren sind zum zu eng gefasst und verpassen zu viele Sendungen.
Auf einigen (wenigen) Seiten gibt es keinen "alle Folgen" link aber Videos. Diese werden jetzt durchgereicht und verarbeitet.
Wenn man mehr Daten crawlt muss man aber auch an der ein oder anderen Stelle mehr abfangen (z.B. href mit java script).
Insgesamt hat der crawler in dev nur 2k Sendungen gefunden. Mit diesen Änderungen sind wir wieder bei ~5k (wie der alten crawler).

Develop kika - Filesize, Dauer und mehr Filme

---

src/main/java/de/mediathekview/mserver/crawler/arte/ArteConstants.java
src/main/java/de/mediathekview/mserver/crawler/arte/tasks/ArteSubcategoryVideosTask.java
src/main/java/de/mediathekview/mserver/crawler/arte/tasks/ArteTaskBase.java

Der Crawler berücksichtigt die Folgeseiten der Subcategories nicht weil result.getNextPageId immer leer ist.
Man kann nur vermuten, dass es noch weitere Seiten gibt über:
result.getUrls().size() == ArteConstants.SUBCATEGORY_LIMIT
Um die 429 (too many request) abzuschwächen habe ich (wie im alten Crawler) einen retry eingebaut.
Offtopic....
Die PageNumber in dieser Klasse habe ich entfernt weil das so nicht wirklich funktioniert.
Das Task wird für mehrere Subcategories verwendet, was dann dazu führt, dass die PageNumber über die Subcategories hinweg hochgezählt wird (Subcategory A Page 1 / A Page 2 / B Page 3). Eigentlich müsste man vorher die Eingangsqueue splitten und dann pro Subcategory eine Instanz bauen...alles etwas schwierig...

nextPageId is missing even if there are subpages

---

src/main/java/de/mediathekview/mserver/crawler/zdf/json/ZdfDownloadDtoDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/zdf/json/ZdfFilmDetailDeserializer.java

Bei 3Sat ist mir aufgefallen, dass viele VideoUrls nicht gefunden werden.
Es fehlt das "ptmd-template". Das segment gibt es nochmal unter Stream. 
Deshalb hier eine Lösung die das Element (wenn nicht vorhanden) aus Streams nimmt.
Beim testen konnte ich keinen Unterschied zwischen den beiden URLs finden.
Dabei ist mir dann aber ein Problem im ZdfFilmDetailDeserializer.java aufgefallen.
Fix auch inkludiert.

Develop 3sat zdf

---

MServer-Config.yaml
src/main/java/de/mediathekview/mserver/base/config/CrawlerApiParam.java
src/main/java/de/mediathekview/mserver/base/config/CrawlerUrlType.java
src/main/java/de/mediathekview/mserver/base/config/MServerConfigDTO.java
src/main/java/de/mediathekview/mserver/crawler/funk/FunkUrls.java
src/main/java/de/mediathekview/mserver/crawler/funk/tasks/FunkVideosToFilmsTask.java
src/test/java/de/mediathekview/mserver/crawler/funk/NexxCloudSessionInitiationTaskTest.java
src/test/resources/MServer-JUnit-Config.yaml

Mit diesem PR können variable über die Konfigdatei des crawler hinzugefügt werden.
Hier erstmal exemplarisch für einen Token der sich in den letzten 3 Monaten geändert hatte.
Später können dann andere parameter folgen.

added ApiParams, rename variable for nexxcloud

---

src/main/java/mServer/crawler/sender/zdf/AbstractZdfCrawler.java
src/main/java/mServer/crawler/sender/zdf/ZdfConstants.java
src/main/java/mServer/crawler/sender/zdf/ZdfCrawler.java
src/main/java/mServer/crawler/sender/zdf/parser/ZdfLetterListHtmlDeserializer.java
src/main/java/mServer/crawler/sender/zdf/parser/ZdfTopicPageHtmlDeserializer.java
src/main/java/mServer/crawler/sender/zdf/parser/ZdfTopicsPageHtmlDeserializer.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfLetterListHtmlTask.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfTopicPageHtmlTask.java
src/main/java/mServer/crawler/sender/zdf/tasks/ZdfTopicsPageHtmlTask.java

in der ZDF-Mediathek wird jetzt der Bereich "Sendungen A-Z" zusätzlich durchsucht, wenn ein langer Lauf ausgeführt wird.
Dies hat zur Folge, dass knapp die doppelte Menge an ZDF-Sendungen gefunden wird.
Löst die Probleme mit alten Sendungen, die in MV nicht (mehr) zu finden sind aber in der ZDF-Mediathek vorhanden sind.
Ich vermute, dass wird die Laufzeit des ZDF-Crawlers ungefähr verdoppeln. Nach den aktuellen Logs wird der lange Lauf wohl ca. 20 Minuten länger laufen. ZDF wird dann wohl der letzte sein, nicht mehr ARTE.

zdf: add topics search

---

build.gradle
src/main/java/mServer/crawler/sender/ard/ArdTopicInfoDto.java
src/main/java/mServer/crawler/sender/ard/json/ArdTopicPageDeserializer.java
src/main/java/mServer/crawler/sender/ard/tasks/ArdTopicPageTask.java

fix für [Forumseintrag](https://forum.mediathekview.de/topic/4638/fehlende-sendung-kinderlandverschickung)
eine manuelle Lösung, aber damit lassen sich alle Unterseiten eines ARD-Themas temporär lesen
die Laufzeit des Crawlers wird nicht groß beeinflusst.
Wenn der Nachtlauf erfolgreich war, werde ich die Liste der Topics wieder leeren.

ARD: load all retro subpages

---

build.gradle
src/main/java/mServer/crawler/AddToFilmlist.java
src/main/java/mServer/crawler/sender/arte/ArteProgramIdToDatenFilmCallable.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

arte fixes

---

src/main/java/de/mediathekview/mserver/base/utils/UrlUtils.java
src/main/java/de/mediathekview/mserver/crawler/srf/parser/SrfFilmJsonDeserializer.java
src/test/java/de/mediathekview/mserver/crawler/srf/parser/SrfFilmJsonDeserializerTest.java

Fix für sich ändernde parameter in der video url für develop.
Hier gab es allerding noch eine nötigen fix für getUrlParameters weil die Funktion mit den heutigen SRL Parametern nicht zurecht kommmt. Weiter details zu den urls in #904

Remove unneeded parameter from videourl for SRF (develop)

---

MServer-Config.yaml
src/main/java/de/mediathekview/mserver/base/config/Log4JConfigurationFactory.java
src/main/java/de/mediathekview/mserver/base/config/MServerConfigDTO.java
src/main/java/de/mediathekview/mserver/base/config/MServerConfigManager.java
src/main/java/de/mediathekview/mserver/base/utils/CheckUrlAvailability.java
src/main/java/de/mediathekview/mserver/crawler/CrawlerManager.java
src/main/java/de/mediathekview/mserver/crawler/basic/IgnoreFilmFilter.java
src/main/java/de/mediathekview/mserver/crawler/dw/DWTaskBase.java
src/main/java/de/mediathekview/mserver/crawler/funk/json/FunkVideoDeserializer.java
src/main/java/de/mediathekview/mserver/crawler/sr/tasks/SrFilmDetailTask.java
src/main/java/de/mediathekview/mserver/crawler/sr/tasks/SrRateLimitedDocumentTask.java
src/main/java/de/mediathekview/mserver/crawler/zdf/tasks/ZdfTaskBase.java
src/main/java/de/mediathekview/mserver/ui/config/MServerConfigUI.java
src/main/resources/MServer-Config.yaml
src/test/java/de/mediathekview/mserver/crawler/CrawlerManagerImportFilmlistsTest.java
src/test/java/de/mediathekview/mserver/crawler/CrawlerManagerLivestreamTest.java
src/test/java/de/mediathekview/mserver/crawler/CrawlerManagerTest.java
src/test/java/de/mediathekview/mserver/crawler/ard/json/ArdTopicPageDeserializerTest.java
src/test/java/de/mediathekview/mserver/crawler/zdf/parser/ZdfTopicsPageHtmlDeserializerTest.java

Remove static cralwermanager - was only used in test cases
Pin config in log4jfactory
Avoid building new config instance in some cases
Remove workaround for static crawlermanager in test cases
Restructure main to allow passing configfile to configurationmanager
update test cases and remove some unused imports

update configurationmanager to support configuration file name

---

src/main/java/mServer/crawler/sender/ard/json/ArdTopicsLetterDeserializer.java

ARD: ignore zdf entries

---

src/main/java/de/mediathekview/mserver/crawler/orfon/json/OrfOnEpisodeDeserializer.java

ORF add parsevideofromthumbnail

---

build.gradle
src/main/java/mServer/crawler/sender/ard/json/ArdFilmDeserializer.java
src/main/java/mServer/crawler/sender/base/Qualities.java
src/main/java/mServer/crawler/sender/zdf/json/ZdfFilmDetailDeserializer.java

fix for 
#992 
#991 
#990 
#989

hotfix 992-991-990-989

---

build.gradle
src/main/java/mServer/crawler/sender/ard/ArdCrawler.java
src/main/java/mServer/crawler/sender/ard/tasks/ArdTopicPageTask.java

quick fix #969

---

build.gradle
src/main/java/mServer/crawler/sender/arte/ArteVideoDeserializer.java

arte: fix url protocols

---

src/main/java/mServer/crawler/sender/arte/ArteListBaseDeserializer.java

ARTE: replace non reachable host in link

---

src/main/java/mServer/crawler/sender/zdf/ZdfConfiguration.java

#1039 
@alex1702 ein Hack, mit dem der alte ZDF-Crawler noch läuft, damit ich mehr Zeit für die Umstellung auf die neue Mediathek habe.

temporary fix for old zdf mediathek

---

src/main/java/mServer/crawler/AddToFilmlist.java
src/main/java/mServer/crawler/sender/ard/ArdCrawler.java
src/main/java/mServer/crawler/sender/ard/json/ArdFilmDeserializer.java
src/test/developTest/java/mServer/crawler/AddToFilmlistTest.java

fixes #1038 
benötigt https://github.com/mediathekview/MLib/pull/164

ARD: own sender for ONE, ARDalpha and tagesschau24
